
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 46345952120-r5fqgpsja6j3r8uu49k4k864nb7e3b5u.apps.googleusercontent.com
            client-secret: 8Vzh1vZsm7iAA-MWPeQm6WgC
            scope: profile, email
